const components = {
  "DeckViewPage": "AppComponents",
  "FlashcardCreator": "AppComponents",
  "HomePage": "AppComponents",
  "Playground": "AppComponents",
  "Button": "Visual",
  "Card": "Visual",
  "Checkbox": "Visual",
  "CodeVisualizer": "Visual",
  "Details": "Visual",
  "DropDown": "Visual",
  "Flashcard": "Visual",
  "FlashcardModal": "Visual",
  "Grid": "Visual",
  "Icon": "Visual",
  "Input": "Visual",
  "Layout": "Visual",
  "Loading": "Visual",
  "MultiRoute": "Visual",
  "Navbar": "Visual",
  "NotFound": "Visual",
  "Route": "Visual",
  "Select": "Visual",
  "Switch": "Visual",
  "TreeItem": "Visual",
  "TreeView": "Visual",
  "CardRenderer": "Service",
  "FetchManager": "Service",
  "IndexedDbManager": "Service",
  "Link": "Service",
  "LocalStorageManager": "Service",
  "StorageService": "Service",
  "Translator": "Service"
};

export default components;
